### ISSUE TITLE
cfg_attr generating (compiler flag) feature(XYZ)

### ISSUE THREAD

**Issue by peter-kehl** [rust-lang/reference#1296]
Hi Docs team,

One gem, and very hard to figure out: Having [`cfg_attr`](https://doc.rust-lang.org/nightly/reference/conditional-compilation.html#the-cfg_attr-attribute) generate a compiler/experimental language feature flag (not a crate feature flag), like (generated code): `#![feature(associated_type_defaults)]`.

For example, if we want test-only functions/code to use associated type defaults, we can have `#![cfg_attr(test, feature(associated_type_defaults))]`. But figuring out how to write that, and that is is actually possible at all, took long. It's not mentioned or obvious from `cfg_attr` docs at all. `cfg_attr` docs do mention `feature`, but only on the condition (left) side (and that's the library crate `feature`(-s), not compiler/experimental language `feature`-s), but not mentioned that & how it can be on the generated code (right) side.

Suggest adding a paragraph and an example, like (feel free to adjust, of course):

At the crate's top level, `cfg_attr` can also generate a `feature` statement that enables compiler/language experimental/unstable features. For example `#![cfg_attr(test, feature(associated_type_defaults))]` generates `#![feature(associated_type_defaults)]` if compiled as a part of tests.

If this sounds OK, I'm willing to provide a PR.

Suggest also referring to it, and vice-versa, from https://doc.rust-lang.org/nightly/unstable-book. Or do you know of any particular page in the `unstable-book`, or any other page to refer to & from? (If this sounds OK or likely to go through, I'm willing to lodge a ticket there, cross-reference, and create a PR.)

**Comment by Havvy** [comment]
The `feature` attribute isn't mentioned at all in the reference because it's only used on unstable Rust and the reference does not document unstable things.

Also, what you are looking for isn't really documented specifically because for `cfg_attr`, the previous mentioned thing but also because it's another specific example of the general functionality and we have an example using `path` already. For `feature`, it's because there's nothing really special about how `cfg_attr` works with it.

Perhaps a reminder that it's possible in the unstable book wouldn't be amiss though.

In any case, we're not going to mention the `feature` attribute in the reference, so I am closing this issue.

**Comment by peter-kehl** [comment]
Agree about no need to document (unstable) `#![cfg_attr(test, feature(associated_type_defaults))]`.

However, the `path = "some-file-path.rs"` example is specific to (few) attributes in format `#[attrib_name = some_value]`. Furthermore, it doesn't document how to use it with attributes that take the value in parenthesis, like `repr(transparent)`. The `path` example can lead people into trying e.g. `#[cfg_attr(debug_assertions, repr = "transparent")]`, which fails.

The correct way for attributes with parenthesis is like `#[cfg_attr(debug_assertions, repr(transparent))]`. That may be obvious to you, but the existing example with `path` doesn't show that. Attributes with parenthesis are more common, so if someone didn't use `path` attrib before, they'll be confused/misled.
