### ISSUE TITLE
PDF export

### ISSUE THREAD

**Issue by yaroslavyaroslav** [rust-lang/reference#1306]
Is there a way to made an PDF version of those docs? I found the print button on the hosted version, but getting PDF this way crops the TOC, which is more than useful in such kind of doc.

**Comment by ehuss** [comment]
I'm not sure what you mean by cropping the TOC, but I believe the print page doesn't currently support the TOC.

If you want to build the documentation yourself, you can use something like [mdbook-pdf](https://github.com/HollowMan6/mdbook-pdf) or [mdbook-latex](https://github.com/lbeckman314/mdbook-latex).

Otherwise there isn't a directly available version of the PDF. I'm going to close since this is an issue for mdbook.
