### ISSUE TITLE
UnsafeBlockExpression and AsyncBlockExpression are classified differently

### ISSUE THREAD

**Issue by adalibas** [rust-lang/reference#1316]
Section 8.2 Expressions: Expression has two production rules i.e. ExpressionWithBlock and ExpressionWithoutBlock.

While UnsafeBlockExpressions are produced via ExpressionWithBlock rule, AsyncBlockExpressions are produced via ExpressionWithoutBlock.

Is this discrepancy intentional?  I do not see how they are syntactically different.

**Comment by ehuss** [comment]
It is not clear if it was originally intended to be different.  One way to look at it is that an async block is similar to a closure, and thus it seems like parsing them in a similar way makes some sense.

Syntactically, it just means that when used as a statement, it must end with `;`, in a match arm end with a `,`. In practice this is almost never an issue since it is usually followed by `.await`.  One could also argue that it helps avoid a mistake such as:

```rust
async {/*...*/} // Oops, async block doesn't actually do anything.
println!("hi"); // ERROR: expected ;
```

See #1267 for more context.

**Comment by ehuss** [comment]
https://internals.rust-lang.org/ is usually the place to go if you want to discuss the design of the language. Generally the reference describes what `rustc` implements.

async blocks are distinctly different from other kinds of blocks since they are not executed, but instead create a value that can be executed. I understand it can seem a little odd since syntactically they look so similar to other blocks kinds. However, they are quite different semantically.

For users, I doubt this syntactic difference will ever register or need to be understood.  I think it should only really matter to parser writers and language lawyers.
