### ISSUE TITLE
In what situation can a variable shadow a constant?

### ISSUE THREAD

**Issue by your-diary** [rust-lang/reference#1365]
According to [*Identifier patterns*](https://doc.rust-lang.org/reference/patterns.html?highlight=shadowing#identifier-patterns),

> *It is an error if `ref` or `ref mut` is specified and the identifier shadows a constant.*

However, the code below ([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=dd820236a4b77c15b4706234c756454e)) doesn't compile though it doesn't contain `ref` or `ref mut`.
```rust
const a: usize = 3;
fn main() {
    let a = 0;
}
```

In what situation can a variable without `ref` or `ref mut` shadow a constant?

**Comment by bjorn3** [comment]
According to the rule right before the rule you quoted:

> [Path patterns](https://doc.rust-lang.org/reference/patterns.html?highlight=shadowing#path-patterns) take precedence over identifier patterns.

Your example attempts to match the constant `a` rather than binding it as variable. If you did something like

```rust
const a: () = ();
fn main() {
    let a = ();
}
```

it would have worked with a warning as now the constant `a` infallibly matches against the value `()`. It still doesn't shadow the constant.

```
warning: constant in pattern `a` should have an upper case name
 --> src/main.rs:3:9
  |
3 |     let a = ();
  |         ^ help: convert the identifier to upper case: `A`
```

**Comment by your-diary** [comment]
@bjorn3 I understand it now. Thank you.
