### ISSUE TITLE
Document extern statics

### ISSUE THREAD

**Issue by matthewjasper** [rust-lang/reference#199]
These currently are undocumented. As well as some documentation on the extern blocks page, accessing an extern static needs to be added to unsafety.md

**Comment by ehuss** [comment]
I'm going to close this, since it seems to be mostly addressed (or at least, the basics are in place).  The unsafety note was added in #459 and the start of extern static docs was added in #736.

If I misunderstood the issue, feel free to reopen, or open new issues with more specific notes about things that are missing or incorrect.
