### ISSUE TITLE
 Reference doc on `cfg` does not cover `cfg(feature = "...")`

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/reference#21]
Migrated from https://github.com/rust-lang/rust/issues/34803

--------------------------------------------

Rust appears to support #[cfg(feature = "foo")] to control optional features: Cargo doc.

The Rust reference on cfg does not mention feature: nightly doc.

**Comment by Havvy** [comment]
The [conditional compilation](https://doc.rust-lang.org/nightly/reference/attributes.html#conditional-compilation) section needs to add the `feature` cfg variant. They are used mostly by [cargo](http://doc.crates.io/manifest.html#the-features-section) and there isn't a language feature for turning on and off features, so would have to say something like "The compiler decides which features are enabled and which aren't." But that wording won't work because "the compiler" currently means `rustc` always.
