### ISSUE TITLE
Document expression evaluation order

### ISSUE THREAD

**Issue by Havvy** [rust-lang/reference#248]
See also, https://internals.rust-lang.org/t/rust-expression-order-of-evaluation/2605/32

**Comment by fweimer** [comment]
The referenced discussion is about evaluation order.  Operator precedence is something different, it's about whether `A ⊕ B ⊙ C` is interpreted as `(A ⊕ B) ⊙ C` or `A ⊕ (B ⊙ C)`. That difference applies independently of the order of evaluation of `A`, `B`, and `C`.

**Comment by Havvy** [comment]
This is what opening issues at 1AM does. Title fixed.

**Comment by eloraiby** [comment]
referring #72763: Is this the intended behaviour for a `for x in 0..function(mutable state) { .. }` ?

**Comment by ehuss** [comment]
@eloraiby Yes.  The range is an expression that is constructs a [`Range`](https://doc.rust-lang.org/std/ops/struct.Range.html) value, which captures the bounds when it is constructed.

**Comment by John-Nagle** [comment]
I [brought this up in the help forums,](https://users.rust-lang.org/t/struct-initialization-order-of-evaluation/51514) related to order of structure initialization.

_Tuples are guaranteed to be initialized in order. How about structs? Doing some marshalling. So I have things like_

`let vector3d = Vector3d{x: getnextvalue(); y: getnextvalue(); z: getnextvalue()};`

where "getnextvalue()" is reading a value from some stream and thus has side effects.

_How about the nested case?_

```
let place = Place(pos:  Vector3d{x: getnextvalue(); y: getnextvalue(); z: getnextvalue()),
                         rot: Quaternion(x: getnextvalue(); y: getnextvalue(); z: getnextvalue(), s: getnextvalue()));

```
Consensus seems to be that the structure field initializers are executed left to right, as with tuples and arrays, but no spec actually _says_ that. It's probably worth nailing down, so some later optimization doesn't break that assumption. For example, if I have

`struct Vector3 {x: f32, y: f32, z: f32}`

and then initialize with

`let v = Vector3(z: getnextvalue(), y: getnextvalue(), x: getnextvalue());
`
the compiler might conceivably do the initialization in structure order rather than initializer order. Since this sort of thing would lead to subtle optimizer-related bugs, it's probably best to prohibit it.

A [Reddit discussion four years ago](https://www.reddit.com/r/rust/comments/3vgvs2/question_about_execution_order_and_struct/) indicated confusion over this issue. Nobody is totally sure.
