### ISSUE TITLE
Document RFC 0879 (small-base-lexing) and RFC 0463 (future-proof-literal-suffixes)

### ISSUE THREAD

**Issue by alercah** [rust-lang/reference#298]
[RFC 0879](https://github.com/rust-lang/rfcs/tree/master/text/0879-small-base-lexing.md)
[RFC 0463](https://github.com/rust-lang/rfcs/blob/master/text/0463-future-proof-literal-suffixes.md

**Comment by kubycsolutions** [comment]
Just checking my understanding: You're saying that the lexer sees `0b110127` as a malformed token rather than a BIN_LITERAL immediately followed by a DEC_LITERAL as the documentation suggests it should?

If so, are you sure you want to change the doc rather than the lexer?

**Comment by mattheww** [comment]
The current documentation is correct for numeric literals (and what it says is that 0b110127 is a [reserved form][1]).

This issue is still open because literal suffixes on string literals aren't completely documented.

[1]: https://doc.rust-lang.org/reference/tokens.html#reserved-forms-similar-to-number-literals
