### ISSUE TITLE
Explicitly describe temporary drop order difference between `return expr;` and final block expression

### ISSUE THREAD

**Issue by Havvy** [rust-lang/reference#452]
Due to temporaries in the final expression of a block living longer than the block expression itself, there's actually a difference between a return expression and the final expression in a block. This should be explicitly documented so that we can link to people about it.

Associated Rust issue: https://github.com/rust-lang/rust/issues/21114

**Comment by pnkfelix** [comment]
Its probably worth expanding this issue to also cover the difference between `{ ...; EXPR }` and `{ ...; let x = EXPR; x }`.

(To which many might say "... there's a *difference* between those two?" Yes, and its similar to the difference cited in this issues title.)

For the start of a neat test for illustrating this, you might look at the tests I added related to rust-lang/rust#54556, such as https://github.com/rust-lang/rust/blob/master/src/test/ui/nll/issue-54556-stephaneyfx.rs. Its diagnostic output under NLL tries hard to explain what the issue is:

https://github.com/rust-lang/rust/blob/b1ca3907e00211b2f645133af3574ca22e4f4f4d/src/test/ui/nll/issue-54556-stephaneyfx.nll.stderr#L1-L15
