### ISSUE TITLE
Document restrictions on doc comments.

### ISSUE THREAD

**Issue by ehuss** [rust-lang/reference#571]
There are various restrictions where doc comments may be placed. The valid and invalid locations should be documented.

Document `Error::UselessDocComment`

```rust
{
    /// This is not valid
}
```

Another restrictions I can think of: Inner attributes cannot follow doc comments.

```rust
{
    /// This doc comment is not allowed.
    #![allow(unused)]
    let x = 1;
}

```

I'm not sure what all the rules are, but they should be documented.

**Comment by petrochenkov** [comment]
The first one is invalid because doc comments are attributes in disguise, they are accepted in exactly same position as attributes.

The second one is invalid because an inner attribute is placed after an outer attribute (the doc one), and inner attributes cannot be placed after outer attributes.

This works, however.
```rust
fn main() {
    //! Doc
    #![rustfmt::zzz]
}
```

**Comment by ehuss** [comment]
Yea, I think this is sufficiently covered by https://doc.rust-lang.org/nightly/reference/comments.html#doc-comments.
