### ISSUE TITLE
Move Repository To rust-lang

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/reference#704]
Hello, the current `rust-lang-nursery` organisation is considered deprecated, and the Rust Programming Language organisation is trying to consolidate managing Rust's GitHub organisations, as such we'd like you to consider moving your repository to the main `rust-lang` organisation instead. 

### How Do I Move To `rust-lang`?
You won't be able to transfer your repository directly, you'll need to transfer your repository to @Mark-Simulacrum, who will then move your repository to the `rust-lang` organisation.

### Deprecating
If you no longer intend to maintain this repository, please let us know and we will take of deprecating the project.

**Comment by steveklabnik** [comment]
I've been meaning to do this, but needed to take some time to make sure stuff won't break.

Given that I'm on core, I should be able to do this myself, I'd imagine.

I'll take some time to investigate this week.

**Comment by XAMPPRocky** [comment]
@steveklabnik Thank you! I'm unaware of the exact GitHub permissions given to core team, but if you are able to do this you should be able to do so following this guide. https://help.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by ehuss** [comment]
I *think* CI will need a migration, I don't know if Travis is still enabled on the `rust-lang` org.  Does anyone know?

I'd be happy to migrate to GitHub Actions if Travis might cause issues.  I just did it for mdbook, so it's still pretty fresh in my head, and the reference CI is substantially simpler.

Otherwise I can't think of anything that will have problems. We don't use gh-pages, or anything that will matter. I also think the git module on rust-lang/rust should be fine with the redirect.

**Comment by steveklabnik** [comment]
> I'd be happy to migrate to GitHub Actions if Travis might cause issues. I just did it for mdbook, so it's still pretty fresh in my head, and the reference CI is substantially simpler.

Yeah, doing this move seems good too.

**Comment by ehuss** [comment]
I posted #705 with the update.  I can't push or self-approve, so someone else needs to merge it.  I tested on my own fork, and it seems to work.

**Comment by steveklabnik** [comment]
After that's merged, I've transferred the repo, added core and lang, and verified the latest commit builds. Looks like we're good to go 👍 

Thanks for the assist @ehuss
