### ISSUE TITLE
Rust-docs permanently missing for arm7 tier2 platform?

### ISSUE THREAD

**Issue by progman1** [rust-lang/reference#755]
I develop on a raspberry pi (armv7-unknown-linux-gnueabihf) which is tier2
and there are understandably missing components for it.
but why would the component rust-docs not be available on this platform (or indeed any other )?
isn't it just a colectionh of html files and therefore platform independent?
I ask because I understand docs can be got to directly with cargo, if this component is installed.

thanks.

**Comment by lzutao** [comment]
This repo isn't place to ask.
Short answer is because of for conditional compilation.

**Comment by progman1** [comment]
Thanks. Where is best? 
In what way is linux/arm7 not capable of conditional compilation?

**Comment by Mark-Simulacrum** [comment]
Rust documentation is generated per-target (since `#[cfg(...)]` affects the content). That means every target we generate documentation for adds CI time, and we do not have the CI time budget for these targets right now, so we don't generate documentation for them ourselves. You should mostly be able to use the tier-1 documentation, as the standard library's user-facing docs are for the most part not platform specific.

As noted previously, if you have further questions, please direct them to internals.rust-lang.org; this is the wrong place for questions; we try to keep the issue tracker solely to bugs.
