### ISSUE TITLE
Update proc-macro note in extern-prelude section

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/reference#789]
The procedural macro examples use `extern crate proc_macro;` which as of `1.42.0` is no longer required. https://doc.rust-lang.org/reference/procedural-macros.html

**Comment by Centril** [comment]
`extern crate` is still required by the language itself as it doesn't put the crate into the extern prelude. What has changed is that Cargo now puts the crate into the extern prelude, but that's not part of the language.

**Comment by XAMPPRocky** [comment]
TIL, it's a bit annoying since the reference is the first result people find when searching, but not the worst so I guess we can close.

**Comment by ehuss** [comment]
Yea, I don't really care one way or the other for the examples.

Ideally we could use better user-level documentation for proc-macros (maybe a dedicated book!).   TRPL could mention it, though I'm not sure it is super important. 

The note on https://doc.rust-lang.org/reference/items/extern-crates.html#extern-prelude needs to be updated, though.  It's been on my todo list for a while.  I really should file issues instead of jotting notes.
