### ISSUE TITLE
proc_macro_attribute dependency

### ISSUE THREAD

**Issue by exellian** [rust-lang/reference#866]
Let's assume you have two user defined proc_macro_attributes in the following order:
```rust
struct Test {}

#[depends_on_inner]
impl Test {

    #[inner]
    fn test() {

    }
}
```

Is there any way to hand over information between these two macro executions, so that depends_on_inner knows that impl Test has a function with a #[inner] attribute?

**Comment by ehuss** [comment]
I'm uncertain if there's a common way to relay information.  `depends_on_inner` can parse its input and notice the presence of the `inner` attribute, but I'm uncertain if that's guaranteed (see #692 and its linked issues).

Questions like these should be asked on one of the user forums, like https://users.rust-lang.org/.

**Comment by exellian** [comment]
Ok thanks!

**Comment by Caellian** [comment]
For future reference if anyone stumbles upon this issue:

Instead of defining `#[inner]` as a separate macro, process it (assuming you're using syn) by detecting it from `ImplItem::attributes` and then passing it to the same processor fn you otherwise would. If you need `#[inner]` to work on its own you must name it differently as order of expansion is not guaranteed and might change depending on target/version.
