### ISSUE TITLE
Document Namespaces

### ISSUE THREAD

**Issue by Havvy** [rust-lang/reference#924]
N.B.: This is a subpart of #568.

@ehuss: you state in #921 that they started an outline for this. Do you still have it, and if so, are you willing to show it?

If this is as daunting as you think it is, should we create a new branch to work on it?

**Comment by ehuss** [comment]
I found a branch where I had started here: https://github.com/ehuss/reference/commit/bb2e84bf3b84f4e7a9b2532feae82659c603d894

Since I think name resolution is a fairly meaty topic, I was thinking that it would be a good idea to separate it into separate files from the start with roughly that outline.  One way to move forward on this is to just add [`resolve/name-resolution.md`](https://github.com/ehuss/reference/blob/name-resolution/src/resolve/name-resolution.md) which gives a vague introduction, and [`resolve/namespaces.md`](https://github.com/ehuss/reference/blob/name-resolution/src/resolve/namespaces.md), since I think the concept of namespaces is pretty straightforward and not too hard to document.

**Comment by Havvy** [comment]
I'm of the opinion that anything is better than nothing and both of those pages look fine as is (modulo my wondering if "name resolution" is the _best_ name). A starting point also makes it easier for others to contribute as well.
